CREATE TABLE IF NOT EXISTS membros (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT UNIQUE,
    cpf TEXT UNIQUE NOT NULL,
    cargo TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS planos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descricao TEXT,
    preco DECIMAL(10,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    conteudo TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    data TIMESTAMPTZ NOT NULL,
    descricao TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE membros ENABLE ROW LEVEL SECURITY;
ALTER TABLE planos ENABLE ROW LEVEL SECURITY;
ALTER TABLE mensagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE eventos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Membros visíveis para autenticados" ON membros 
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Usuário edita próprio perfil" ON membros 
    FOR UPDATE TO authenticated USING (auth.uid() = id);

CREATE POLICY "Planos visíveis para todos" ON planos 
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Mensagens visíveis para autenticados" ON mensagens 
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Usuário cria própria mensagem" ON mensagens 
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "Usuário gerencia própria mensagem" ON mensagens 
    FOR ALL TO authenticated USING (auth.uid() = usuario_id);

CREATE POLICY "Eventos visíveis para todos" ON eventos 
    FOR SELECT TO authenticated USING (true);

CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.membros (id, nome, email, cpf)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.email, 
    new.raw_user_meta_data->>'cpf'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
